name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-on-linux-with-llvm-14:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install LLVM
        run: |
          echo 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal-15 main' | sudo tee /etc/apt/sources.list.d/llvm.list
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo apt-get update
          sudo apt-get install --no-install-recommends llvm-15-dev
      
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
         go-version: 1.20.x

      - name: Go mod download
        run: go mod download

      - name: Build
        run: go build -v -tags=llvm15 ./...

      - name: Test
        run: go test -v -tags=llvm15 ./...