name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-on-ubuntu-with-llvm-20:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install LLVM 20
        run: |
          echo 'deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-20 main' | sudo tee /etc/apt/sources.list.d/llvm.list
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends llvm-20 llvm-20-dev

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.x

      - name: Build
        run: go build -tags=llvm20 ./...

      - name: Unit tests
        run: go test -tags=llvm20 ./pkg/...

      - name: Integration tests (execute generated code)
        run: go test -tags=llvm20 ./integration/...
        env:
          LLC: llc-20

      - name: Make integration flow (llc-20 + cc)
        run: make testllvmcode
        env:
          LLC: llc-20
